CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	fb_id VARCHAR(20) NOT NULL UNIQUE,
	first_name VARCHAR(20),
	last_name VARCHAR(20),
	is_subscribed BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE IF NOT EXISTS grade_subscribers (
  id INT AUTO_INCREMENT PRIMARY KEY,
	fb_id VARCHAR(20) NOT NULL,
	student_code VARCHAR(20) NOT NULL
);